In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
outcome_1 = pd.read_csv('../data/outcome1_a.csv')

outcome_2 = pd.read_csv('../data/outcome2_a.csv')

outcome_3 = pd.read_csv('../data/outcome3_a.csv')

pc_a = pd.concat([outcome_1, outcome_2, outcome_3], ignore_index=True)

id3 = pc_a['Student TEIDS ID']

In [3]:
pc_a.head()

,Unnamed: 0,Student TEIDS ID,USE_ENTRANCE_DQScore_Adaptive,USE_ENTRANCE_DQScore_Cognitive,USE_ENTRANCE_DQScore_Communication,USE_ENTRANCE_DQScore_Motor,USE_ENTRANCE_DQScore_Social,USE_ENTRANCE_ZScore_Adaptive,USE_ENTRANCE_ZScore_Adaptive-Self_Care,USE_ENTRANCE_ZScore_Adaptive-Personal_Responsibility,...,EXIT_Cognitive-Perception and Concepts Z-Score,EXIT_Cognitive-Perception and Concepts T-Score,EXIT_Cognitive-Perception and Concepts NCE,social_category,adaptive_category,outcome2_entrance_DQ,outcome2_exit_DQ,outcome2_subdomain_check,outcome2_category,outcome3_category
0,6,486067,93.0,74.0,75.0,77.0,77.0,-0.47,-1.00,0.00,...,1.0,40.0,29,a,a,NaN,NaN,NaN,NaN,NaN
1,13,490309,88.0,65.0,55.0,66.0,88.0,-0.80,-2.33,0.67,...,3.0,20.0,<1,a,a,NaN,NaN,NaN,NaN,NaN
2,502,520001,95.0,83.0,65.0,85.0,95.0,-0.33,-0.33,-0.33,...,3.0,20.0,<1,a,a,NaN,NaN,NaN,NaN,NaN
3,544,522186,60.0,58.0,55.0,73.0,83.0,-2.67,-2.67,0.00,...,2.0,30.0,8,a,a,NaN,NaN,NaN,NaN,NaN
4,613,523762,55.0,67.0,55.0,63.0,75.0,-3.00,-3.00,0.00,...,3.0,20.0,<1,a,b,NaN,NaN,NaN,NaN,NaN

In [4]:
id3.head()

0    486067
1    490309
2    520001
3    522186
4    523762
Name: Student TEIDS ID, dtype: int64